FROM denoland/deno:bin-2.8.2 AS deno-bin

FROM python:3.13-slim-trixie

COPY --from=deno-bin /deno /usr/local/bin/deno

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY "./livestream_saver/" ./livestream_saver/
COPY "livestream_saver.py" .

# Provide default config files, but this directory path should be mounted instead
# and these files should be replaced (masked) with user-specific configurations.
COPY "./config/ytdlp_config.json" "/root/.config/livestream_saver/ytdlp_config.json"
COPY "./config/livestream_saver.cfg" "/root/.config/livestream_saver/livestream_saver.cfg"
COPY "./config/.env" "/root/.config/livestream_saver/.env"

COPY "./docker/entrypoint.sh" ./entrypoint.sh
RUN chmod +x ./entrypoint.sh

ENV LSS_OUTPUT_DIR="/downloads"
ENV LSS_CONFIG_DIR="/root/.config/livestream_saver"
ENV LSS_COOKIES_FILE="/root/.config/livestream_saver/cookies.txt"

ENTRYPOINT [ "./entrypoint.sh" ]

CMD [ "monitor", ]
